"""CosyVoice2_Emotion: Emo-FiLM 推理 API 入口。

用法:
    cv2 = CosyVoice2_Emotion(model_dir)
    for chunk in cv2.inference_emo_film(
        text_with_emo="<emotion type='hap' intensity='high'>Hello!</emotion>",
        prompt_text="reference text",
        prompt_wav_path="/path/to/prompt.wav",
    ):
        torchaudio.save("out.wav", chunk['tts_speech'].cpu(), cv2.sample_rate)
        break
"""
import os
import logging
import torch
from hyperpyyaml import load_hyperpyyaml
from modelscope import snapshot_download

from cosyvoice.cli.cosyvoice import CosyVoice2
from cosyvoice.cli.model_emo import CosyVoice2Model_Emotion
from cosyvoice.cli.frontend_emo import CosyVoiceFrontEnd_Emotion

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))


class CosyVoice2_Emotion(CosyVoice2):
    def __init__(self, model_dir, **kwargs):
        self.model_dir = model_dir
        self.fp16 = kwargs.get("fp16", False)
        if not os.path.exists(model_dir):
            model_dir = snapshot_download(model_dir)

        # spec 11.5：相对路径 `cli/cosyvoice_emo.py` → `..`/`..` 上跳至项目根 → `conf/emo_film.yaml`
        # **依赖前置条件**：Plan 2 Task 6 必须已生成 `conf/emo_film.yaml`
        # 若文件不存在则直接 raise，避免静默回退到 cosyvoice2.yaml 导致配置错乱
        # （回退后 configs['llm'] 会是 Qwen2LM 而非 Qwen2LM_Emotion，emotion_ids kwarg 会被拒收）
        hyper_yaml_path = os.path.join(CURRENT_DIR, "..", "..", "conf", "emo_film.yaml")
        if not os.path.exists(hyper_yaml_path):
            raise FileNotFoundError(
                f"conf/emo_film.yaml not found at {hyper_yaml_path}. "
                f"This file is a prerequisite generated by Plan 2 Task 6. "
                f"Please run Plan 2 first, or set EMOFILM_YAML env var to override."
            )

        with open(hyper_yaml_path, "r") as f:
            self.configs = load_hyperpyyaml(
                f, overrides={"qwen_pretrain_path": os.path.join(model_dir, "CosyVoice-BlankEN")}
            )

        # 关键校验：configs['llm'] 必须是 Qwen2LM_Emotion（防止 yaml 配置错乱）
        assert self.configs["llm"].__class__.__name__ == "Qwen2LM_Emotion", (
            f"conf/emo_film.yaml 加载后 configs['llm'] 应为 Qwen2LM_Emotion，"
            f"实际为 {self.configs['llm'].__class__.__name__}。请检查 yaml 配置。"
        )

        self.sample_rate = self.configs.get("sample_rate", 24000)

        self.model = CosyVoice2Model_Emotion(
            self.configs["llm"], self.configs["flow"], self.configs["hift"], fp16=self.fp16
        )
        self.model.load(
            os.path.join(model_dir, "llm.pt"),
            os.path.join(model_dir, "flow.pt"),
            os.path.join(model_dir, "hift.pt"),
        )

        tokenizer = self.configs["get_tokenizer"]()
        self.frontend = CosyVoiceFrontEnd_Emotion(
            get_tokenizer=lambda: tokenizer,
            feat_extractor=self.configs["feat_extractor"],
            campplus_model=os.path.join(model_dir, "campplus.onnx"),
            speech_tokenizer_model=os.path.join(model_dir, "speech_tokenizer_v2.onnx"),
            allowed_special=self.configs.get("allowed_special", "all"),
        )
        self.tokenizer = tokenizer
        del self.configs

    def inference_emo_film(self, text_with_emo, prompt_text, prompt_wav_path,
                           stream=False, speed=1.0, zero_shot_spk_id=""):
        if stream is True:
            raise NotImplementedError("stream inference not supported for Emo-FiLM")
        # spec 11.4：Emo-FiLM 推理路径依赖 prompt_text + prompt_wav，**不支持预设 spk_id 路径**
        # （父类 frontend_zero_shot 在 spk_id != '' 时返回的 dict 缺 prompt 字段，会破坏 tts）
        if zero_shot_spk_id != "":
            raise NotImplementedError(
                "zero_shot_spk_id is not supported for Emo-FiLM inference. "
                "Use prompt_text + prompt_wav_path for voice cloning."
            )

        model_input = self.frontend.frontend_emo_film(
            text_with_emo, prompt_text, prompt_wav_path,
            self.sample_rate, zero_shot_spk_id,
        )
        for model_output in self.model.tts(**model_input, stream=False, speed=speed):
            yield model_output
